/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/activities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    departmentId?: number;
                    visibility?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateActivityRequest"];
                    "text/json": components["schemas"]["CreateActivityRequest"];
                    "application/*+json": components["schemas"]["CreateActivityRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/activities/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/activities/my-assignments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/activities/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put: {
            parameters: {
                query?: {
                    force?: boolean;
                };
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateActivityRequest"];
                    "text/json": components["schemas"]["UpdateActivityRequest"];
                    "application/*+json": components["schemas"]["UpdateActivityRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/activity-templates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateActivityTemplateRequest"];
                    "text/json": components["schemas"]["CreateActivityTemplateRequest"];
                    "application/*+json": components["schemas"]["CreateActivityTemplateRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/activity-templates/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateActivityTemplateRequest"];
                    "text/json": components["schemas"]["UpdateActivityTemplateRequest"];
                    "application/*+json": components["schemas"]["UpdateActivityTemplateRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/initiate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["InitiateAuthRequest"];
                    "text/json": components["schemas"]["InitiateAuthRequest"];
                    "application/*+json": components["schemas"]["InitiateAuthRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["LoginRequest"];
                    "text/json": components["schemas"]["LoginRequest"];
                    "application/*+json": components["schemas"]["LoginRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/set-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SetPasswordRequest"];
                    "text/json": components["schemas"]["SetPasswordRequest"];
                    "application/*+json": components["schemas"]["SetPasswordRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/password-reset/request": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RequestPasswordResetRequest"];
                    "text/json": components["schemas"]["RequestPasswordResetRequest"];
                    "application/*+json": components["schemas"]["RequestPasswordResetRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/password-reset/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ConfirmPasswordResetRequest"];
                    "text/json": components["schemas"]["ConfirmPasswordResetRequest"];
                    "application/*+json": components["schemas"]["ConfirmPasswordResetRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/google-login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    returnUrl?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/google-callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    returnUrl?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/avatars/{userId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    userId: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    userId: number;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/x-www-form-urlencoded": {
                        ContentType?: string;
                        ContentDisposition?: string;
                        Headers?: {
                            [key: string]: string[];
                        };
                        /** Format: int64 */
                        Length?: number;
                        Name?: string;
                        FileName?: string;
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/calendar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    start?: string;
                    end?: string;
                    departmentIds?: number[];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateChurchConfigRequest"];
                    "text/json": components["schemas"]["UpdateChurchConfigRequest"];
                    "application/*+json": components["schemas"]["UpdateChurchConfigRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/config/admin": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/departments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateDepartmentRequest"];
                    "text/json": components["schemas"]["CreateDepartmentRequest"];
                    "application/*+json": components["schemas"]["CreateDepartmentRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/departments/with-staffing": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/departments/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateDepartmentRequest"];
                    "text/json": components["schemas"]["UpdateDepartmentRequest"];
                    "application/*+json": components["schemas"]["UpdateDepartmentRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/departments/{departmentId}/sub-ministries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    departmentId: number;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateSubMinistryRequest"];
                    "text/json": components["schemas"]["CreateSubMinistryRequest"];
                    "application/*+json": components["schemas"]["CreateSubMinistryRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/departments/{departmentId}/sub-ministries/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    departmentId: number;
                    id: number;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateSubMinistryRequest"];
                    "text/json": components["schemas"]["UpdateSubMinistryRequest"];
                    "application/*+json": components["schemas"]["UpdateSubMinistryRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    departmentId: number;
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/program-schedules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateProgramScheduleRequest"];
                    "text/json": components["schemas"]["CreateProgramScheduleRequest"];
                    "application/*+json": components["schemas"]["CreateProgramScheduleRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/program-schedules/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateProgramScheduleRequest"];
                    "text/json": components["schemas"]["UpdateProgramScheduleRequest"];
                    "application/*+json": components["schemas"]["UpdateProgramScheduleRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/public/next-activity": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/public/live-status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/public/upcoming-activities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/public/program-schedules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/public/departments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/public/calendar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    start?: string;
                    end?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/setup-progress": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/system-health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/assignable-officers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    search?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    cursor?: string;
                    limit?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateUserRequest"];
                    "text/json": components["schemas"]["CreateUserRequest"];
                    "application/*+json": components["schemas"]["CreateUserRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateUserRequest"];
                    "text/json": components["schemas"]["UpdateUserRequest"];
                    "application/*+json": components["schemas"]["UpdateUserRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/bulk": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["BulkCreateUsersRequest"];
                    "text/json": components["schemas"]["BulkCreateUsersRequest"];
                    "application/*+json": components["schemas"]["BulkCreateUsersRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/guests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateGuestRequest"];
                    "text/json": components["schemas"]["CreateGuestRequest"];
                    "application/*+json": components["schemas"]["CreateGuestRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ActivityDeletedNotification: {
            /** Format: int32 */
            activityId: number;
            /** Format: int32 */
            departmentId: null | number;
            visibility: string;
            /** Format: date-time */
            timestamp: string;
        };
        ActivityListItem: {
            /** Format: int32 */
            id: number;
            title: string;
            /** Format: date */
            date: string;
            /** Format: time */
            startTime: string;
            /** Format: time */
            endTime: string;
            /** Format: int32 */
            departmentId?: null | number;
            departmentName: string;
            departmentColor: string;
            visibility: string;
            specialType?: null | string;
            isMeeting: boolean;
            /** @enum {unknown} */
            meetingType?: "physical" | "zoom" | null;
            locationName?: null | string;
            /** Format: int32 */
            roleCount: number;
            /** Format: int32 */
            totalHeadcount: number;
            /** Format: int32 */
            assignedCount: number;
            staffingStatus: string;
            /** Format: date-time */
            createdAt: string;
        };
        ActivityNotification: {
            /** Format: int32 */
            activityId: number;
            title: string;
            /** Format: date */
            date: string;
            /** Format: int32 */
            departmentId: null | number;
            visibility: string;
            /** Format: uint32 */
            concurrencyToken: number;
            /** Format: date-time */
            timestamp: string;
            updatedFields?: null | string;
        };
        ActivityResponse: {
            /** Format: int32 */
            id: number;
            title: string;
            description?: null | string;
            /** Format: date */
            date: string;
            /** Format: time */
            startTime: string;
            /** Format: time */
            endTime: string;
            /** Format: int32 */
            departmentId?: null | number;
            departmentName: string;
            departmentAbbreviation: string;
            departmentColor: string;
            visibility: string;
            specialType?: null | string;
            isMeeting: boolean;
            /** @enum {unknown} */
            meetingType?: "physical" | "zoom" | null;
            zoomLink?: null | string;
            locationName?: null | string;
            locationAddress?: null | string;
            roles: {
                /** Format: int32 */
                id: number;
                roleName: string;
                /** Format: int32 */
                headcount: number;
                /** Format: int32 */
                sortOrder: number;
                isCritical: boolean;
                assignments: {
                    /** Format: int32 */
                    id: number;
                    /** Format: int32 */
                    userId: number;
                    firstName: string;
                    lastName: string;
                    avatarUrl?: null | string;
                    isGuest: boolean;
                }[];
            }[];
            staffingStatus: string;
            /** Format: uint32 */
            concurrencyToken: number;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        ActivityRoleInput: {
            /** Format: int32 */
            id?: null | number;
            roleName: string;
            /** Format: int32 */
            headcount: number;
            isCritical?: null | boolean;
            isPredicateur?: null | boolean;
            assignments?: null | components["schemas"]["RoleAssignmentInput"][];
        };
        ActivityRoleResponse: {
            /** Format: int32 */
            id: number;
            roleName: string;
            /** Format: int32 */
            headcount: number;
            /** Format: int32 */
            sortOrder: number;
            isCritical: boolean;
            assignments: {
                /** Format: int32 */
                id: number;
                /** Format: int32 */
                userId: number;
                firstName: string;
                lastName: string;
                avatarUrl?: null | string;
                isGuest: boolean;
            }[];
        };
        ActivityTemplateListItem: {
            /** Format: int32 */
            id: number;
            name: string;
            description?: null | string;
            roleSummary: string;
            /** Format: int32 */
            roleCount: number;
            roles: {
                /** Format: int32 */
                id: number;
                roleName: string;
                /** Format: int32 */
                defaultHeadcount: number;
                /** Format: int32 */
                sortOrder: number;
                isCritical: boolean;
                isPredicateur: boolean;
            }[];
        };
        ActivityTemplateResponse: {
            /** Format: int32 */
            id: number;
            name: string;
            description?: null | string;
            roles: {
                /** Format: int32 */
                id: number;
                roleName: string;
                /** Format: int32 */
                defaultHeadcount: number;
                /** Format: int32 */
                sortOrder: number;
                isCritical: boolean;
                isPredicateur: boolean;
            }[];
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        AssignableOfficerResponse: {
            /** Format: int32 */
            userId: number;
            firstName: string;
            lastName: string;
            avatarUrl?: null | string;
            departments: {
                /** Format: int32 */
                id: number;
                name: string;
                abbreviation: string;
                color: string;
            }[];
        };
        AuthMeResponse: {
            /** Format: int32 */
            userId: number;
            email: string;
            firstName: string;
            lastName: string;
            role: string;
            avatarUrl?: null | string;
            departmentIds: number[];
            departments: {
                /** Format: int32 */
                id: number;
                name: string;
                abbreviation: string;
                color: string;
            }[];
        };
        BulkCreateUsersRequest: {
            users: components["schemas"]["CreateUserRequest"][];
        };
        BulkCreateUsersResponse: {
            created: {
                /** Format: int32 */
                id: number;
                firstName: string;
                lastName: string;
                email: string;
                role: string;
                avatarUrl?: null | string;
                isGuest: boolean;
                departments: {
                    /** Format: int32 */
                    id: number;
                    name: string;
                    abbreviation: string;
                    color: string;
                }[];
                /** Format: date-time */
                createdAt: string;
                /** Format: date-time */
                updatedAt: string;
            }[];
            /** Format: int32 */
            count: number;
        };
        ChurchConfigResponse: {
            /** Format: int32 */
            id: number;
            churchName: string;
            address: string;
            youTubeChannelUrl?: null | string;
            phoneNumber?: null | string;
            welcomeMessage?: null | string;
            defaultLocale: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        CoAssigneeResponse: {
            /** Format: int32 */
            userId: number;
            firstName: string;
            lastName: string;
            avatarUrl?: null | string;
            isGuest: boolean;
        };
        ConfirmPasswordResetRequest: {
            token: string;
            newPassword: string;
        };
        CreateActivityRequest: {
            title: string;
            description?: null | string;
            /** Format: date */
            date: string;
            /** Format: time */
            startTime: string;
            /** Format: time */
            endTime: string;
            /** Format: int32 */
            departmentId: number;
            visibility: string;
            specialType?: null | string;
            /** Format: int32 */
            templateId?: null | number;
            roles?: null | components["schemas"]["ActivityRoleInput"][];
            isMeeting?: null | boolean;
            meetingType?: null | components["schemas"]["MeetingType"];
            zoomLink?: null | string;
            locationName?: null | string;
            locationAddress?: null | string;
        };
        CreateActivityTemplateRequest: {
            name: string;
            description?: null | string;
            roles: components["schemas"]["TemplateRoleRequest"][];
        };
        CreateDepartmentRequest: {
            name: string;
            abbreviation?: null | string;
            color: string;
            description?: null | string;
            subMinistryNames?: null | string[];
        };
        CreateGuestRequest: {
            name: string;
            phone?: null | string;
        };
        CreateProgramScheduleRequest: {
            title: string;
            /** Format: int32 */
            dayOfWeek: number;
            startTime: string;
            endTime: string;
            hostName?: null | string;
            /** Format: int32 */
            departmentId?: null | number;
        };
        CreateSubMinistryRequest: {
            name: string;
            /** Format: int32 */
            leadUserId?: null | number;
        };
        CreateUserRequest: {
            firstName: string;
            lastName: string;
            email: string;
            role: string;
            departmentIds: number[];
        };
        DashboardActivityItem: {
            /** Format: int32 */
            id: number;
            title: string;
            /** Format: date */
            date: string;
            /** Format: time */
            startTime: string;
            /** Format: time */
            endTime: string;
            /** Format: int32 */
            departmentId?: null | number;
            departmentName: string;
            departmentAbbreviation: string;
            departmentColor: string;
            visibility: string;
            specialType?: null | string;
            isMeeting: boolean;
            /** @enum {unknown} */
            meetingType?: "physical" | "zoom" | null;
            locationName?: null | string;
            predicateurName?: null | string;
            predicateurAvatarUrl?: null | string;
            /** Format: int32 */
            roleCount: number;
            /** Format: int32 */
            totalHeadcount: number;
            /** Format: int32 */
            assignedCount: number;
            staffingStatus: string;
        };
        DepartmentListItem: {
            /** Format: int32 */
            id: number;
            name: string;
            abbreviation: string;
            color: string;
            description?: null | string;
            /** Format: int32 */
            subMinistryCount: number;
        };
        DepartmentResponse: {
            /** Format: int32 */
            id: number;
            name: string;
            abbreviation: string;
            color: string;
            description?: null | string;
            subMinistries: {
                /** Format: int32 */
                id: number;
                name: string;
                /** Format: int32 */
                leadUserId?: null | number;
                leadFirstName?: null | string;
                leadLastName?: null | string;
                leadAvatarUrl?: null | string;
            }[];
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        DepartmentWithStaffingListItem: {
            /** Format: int32 */
            id: number;
            name: string;
            abbreviation: string;
            color: string;
            description?: null | string;
            /** Format: int32 */
            subMinistryCount: number;
            /** Format: int32 */
            upcomingActivityCount: number;
            aggregateStaffingStatus: string;
        };
        GuestCreatedResponse: {
            /** Format: int32 */
            userId: number;
            firstName: string;
            lastName: string;
            isGuest: boolean;
        };
        HealthCheckItem: {
            name: string;
            status: string;
            description?: null | string;
            duration: string;
        };
        InitiateAuthRequest: {
            email: string;
        };
        InitiateAuthResponse: {
            flow: string;
        };
        LoginRequest: {
            email: string;
            password: string;
        };
        /** @enum {unknown} */
        MeetingType: "physical" | "zoom" | null;
        MyAssignmentListItem: {
            /** Format: int32 */
            activityId: number;
            activityTitle: string;
            /** Format: date */
            date: string;
            /** Format: time */
            startTime: string;
            /** Format: time */
            endTime: string;
            departmentName: string;
            departmentAbbreviation: string;
            departmentColor: string;
            specialType?: null | string;
            roleName: string;
            coAssignees: {
                /** Format: int32 */
                userId: number;
                firstName: string;
                lastName: string;
                avatarUrl?: null | string;
                isGuest: boolean;
            }[];
        };
        OfficerDepartmentBadge: {
            /** Format: int32 */
            id: number;
            name: string;
            abbreviation: string;
            color: string;
        };
        PagedUserListItem: {
            items: {
                /** Format: int32 */
                id: number;
                firstName: string;
                lastName: string;
                email: string;
                role: string;
                avatarUrl?: null | string;
                departments: {
                    /** Format: int32 */
                    id: number;
                    name: string;
                    abbreviation: string;
                    color: string;
                }[];
                /** Format: date-time */
                createdAt: string;
            }[];
            nextCursor?: null | string;
        };
        ProgramScheduleListItem: {
            /** Format: int32 */
            id: number;
            title: string;
            /** Format: int32 */
            dayOfWeek: number;
            startTime: string;
            endTime: string;
            hostName?: null | string;
            /** Format: int32 */
            departmentId?: null | number;
            departmentName?: null | string;
        };
        ProgramScheduleResponse: {
            /** Format: int32 */
            id: number;
            title: string;
            /** Format: int32 */
            dayOfWeek: number;
            startTime: string;
            endTime: string;
            hostName?: null | string;
            /** Format: int32 */
            departmentId?: null | number;
            departmentName?: null | string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        PublicActivityListItem: {
            /** Format: int32 */
            id: number;
            title: string;
            /** Format: date */
            date: string;
            /** Format: time */
            startTime: string;
            /** Format: time */
            endTime: string;
            departmentName: null | string;
            departmentAbbreviation: null | string;
            departmentColor: null | string;
            predicateurName: null | string;
            predicateurAvatarUrl: null | string;
            specialType: null | string;
        };
        PublicChurchConfigResponse: {
            churchName: string;
            address: string;
            phoneNumber?: null | string;
            welcomeMessage?: null | string;
            youTubeChannelUrl?: null | string;
        };
        PublicDepartmentResponse: {
            /** Format: int32 */
            id: number;
            name: string;
            abbreviation: string;
            color: string;
            description: null | string;
            nextActivityTitle: null | string;
            /** Format: date */
            nextActivityDate: null | string;
            /** Format: time */
            nextActivityStartTime: null | string;
        };
        PublicLiveStatusResponse: {
            isLive: boolean;
            liveVideoId: null | string;
            liveTitle: null | string;
        };
        PublicNextActivityResponse: {
            /** Format: int32 */
            id: number;
            title: string;
            /** Format: date */
            date: string;
            /** Format: time */
            startTime: string;
            /** Format: time */
            endTime: string;
            departmentName: null | string;
            departmentAbbreviation: null | string;
            departmentColor: null | string;
            predicateurName: null | string;
            predicateurAvatarUrl: null | string;
            specialType: null | string;
        };
        PublicProgramScheduleResponse: {
            title: string;
            dayOfWeek: number;
            /** Format: time */
            startTime: string;
            /** Format: time */
            endTime: string;
            hostName: null | string;
            departmentName: null | string;
            departmentColor: null | string;
        };
        RequestPasswordResetRequest: {
            email: string;
        };
        RoleAssignmentInput: {
            /** Format: int32 */
            userId: number;
        };
        RoleAssignmentResponse: {
            /** Format: int32 */
            id: number;
            /** Format: int32 */
            userId: number;
            firstName: string;
            lastName: string;
            avatarUrl?: null | string;
            isGuest: boolean;
        };
        SetPasswordRequest: {
            email: string;
            newPassword: string;
        };
        SetupProgressResponse: {
            steps: {
                id: string;
                status: string;
            }[];
            isSetupComplete: boolean;
        };
        SetupStatusResponse: {
            churchConfigExists: boolean;
            /** Format: int32 */
            departmentCount: number;
            /** Format: int32 */
            templateCount: number;
            /** Format: int32 */
            scheduleCount: number;
            /** Format: int32 */
            userCount: number;
        };
        SetupStepItem: {
            id: string;
            status: string;
        };
        SubMinistryResponse: {
            /** Format: int32 */
            id: number;
            name: string;
            /** Format: int32 */
            leadUserId?: null | number;
            leadFirstName?: null | string;
            leadLastName?: null | string;
            leadAvatarUrl?: null | string;
        };
        SystemHealthResponse: {
            status: string;
            checks: {
                name: string;
                status: string;
                description?: null | string;
                duration: string;
            }[];
            version: string;
            /** Format: int64 */
            uptimeSeconds: number;
            environment: string;
            setupStatus: {
                churchConfigExists: boolean;
                /** Format: int32 */
                departmentCount: number;
                /** Format: int32 */
                templateCount: number;
                /** Format: int32 */
                scheduleCount: number;
                /** Format: int32 */
                userCount: number;
            };
        };
        TemplateRoleRequest: {
            roleName: string;
            /** Format: int32 */
            defaultHeadcount: number;
            isCritical?: null | boolean;
            isPredicateur?: null | boolean;
        };
        TemplateRoleResponse: {
            /** Format: int32 */
            id: number;
            roleName: string;
            /** Format: int32 */
            defaultHeadcount: number;
            /** Format: int32 */
            sortOrder: number;
            isCritical: boolean;
            isPredicateur: boolean;
        };
        UpdateActivityRequest: {
            title: string;
            description?: null | string;
            /** Format: date */
            date: string;
            /** Format: time */
            startTime: string;
            /** Format: time */
            endTime: string;
            /** Format: int32 */
            departmentId: number;
            visibility: string;
            specialType?: null | string;
            /** Format: uint32 */
            concurrencyToken: number;
            roles?: null | components["schemas"]["ActivityRoleInput"][];
            isMeeting?: null | boolean;
            meetingType?: null | components["schemas"]["MeetingType"];
            zoomLink?: null | string;
            locationName?: null | string;
            locationAddress?: null | string;
        };
        UpdateActivityTemplateRequest: {
            name: string;
            description?: null | string;
            roles: components["schemas"]["TemplateRoleRequest"][];
        };
        UpdateChurchConfigRequest: {
            churchName: string;
            address: string;
            youTubeChannelUrl?: null | string;
            phoneNumber?: null | string;
            welcomeMessage?: null | string;
            defaultLocale: string;
        };
        UpdateDepartmentRequest: {
            name: string;
            abbreviation?: null | string;
            color: string;
            description?: null | string;
        };
        UpdateProgramScheduleRequest: {
            title: string;
            /** Format: int32 */
            dayOfWeek: number;
            startTime: string;
            endTime: string;
            hostName?: null | string;
            /** Format: int32 */
            departmentId?: null | number;
        };
        UpdateSubMinistryRequest: {
            name: string;
            /** Format: int32 */
            leadUserId?: null | number;
        };
        UpdateUserRequest: {
            firstName: string;
            lastName: string;
            role: string;
            departmentIds: number[];
        };
        UserDepartmentBadge: {
            /** Format: int32 */
            id: number;
            name: string;
            abbreviation: string;
            color: string;
        };
        UserListItem: {
            /** Format: int32 */
            id: number;
            firstName: string;
            lastName: string;
            email: string;
            role: string;
            avatarUrl?: null | string;
            departments: {
                /** Format: int32 */
                id: number;
                name: string;
                abbreviation: string;
                color: string;
            }[];
            /** Format: date-time */
            createdAt: string;
        };
        UserResponse: {
            /** Format: int32 */
            id: number;
            firstName: string;
            lastName: string;
            email: string;
            role: string;
            avatarUrl?: null | string;
            isGuest: boolean;
            departments: {
                /** Format: int32 */
                id: number;
                name: string;
                abbreviation: string;
                color: string;
            }[];
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
